title: "Blog de Investigación Tecnológica"
description: "Artículos sobre Inteligencia Artificial y Tecnología"
baseurl: "/ia-articulos" # coincide con tu repo
url: "https://johnylozano.github.io"
theme: minima
